// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarList.proto

package net.cardentify.data;

public final class CarListOuterClass {
  private CarListOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CarVectorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.cardentify.data.CarVector)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float vector = 1;</code>
     */
    java.util.List<java.lang.Float> getVectorList();
    /**
     * <code>repeated float vector = 1;</code>
     */
    int getVectorCount();
    /**
     * <code>repeated float vector = 1;</code>
     */
    float getVector(int index);
  }
  /**
   * Protobuf type {@code net.cardentify.data.CarVector}
   */
  public  static final class CarVector extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.cardentify.data.CarVector)
      CarVectorOrBuilder {
    // Use CarVector.newBuilder() to construct.
    private CarVector(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CarVector() {
      vector_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CarVector(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                vector_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000001;
              }
              vector_.add(input.readFloat());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                vector_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                vector_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          vector_ = java.util.Collections.unmodifiableList(vector_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.cardentify.data.CarListOuterClass.internal_static_net_cardentify_data_CarVector_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.cardentify.data.CarListOuterClass.internal_static_net_cardentify_data_CarVector_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.cardentify.data.CarListOuterClass.CarVector.class, net.cardentify.data.CarListOuterClass.CarVector.Builder.class);
    }

    public static final int VECTOR_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Float> vector_;
    /**
     * <code>repeated float vector = 1;</code>
     */
    public java.util.List<java.lang.Float>
        getVectorList() {
      return vector_;
    }
    /**
     * <code>repeated float vector = 1;</code>
     */
    public int getVectorCount() {
      return vector_.size();
    }
    /**
     * <code>repeated float vector = 1;</code>
     */
    public float getVector(int index) {
      return vector_.get(index);
    }
    private int vectorMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getVectorList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(vectorMemoizedSerializedSize);
      }
      for (int i = 0; i < vector_.size(); i++) {
        output.writeFloatNoTag(vector_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getVectorList().size();
        size += dataSize;
        if (!getVectorList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        vectorMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.cardentify.data.CarListOuterClass.CarVector)) {
        return super.equals(obj);
      }
      net.cardentify.data.CarListOuterClass.CarVector other = (net.cardentify.data.CarListOuterClass.CarVector) obj;

      boolean result = true;
      result = result && getVectorList()
          .equals(other.getVectorList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getVectorCount() > 0) {
        hash = (37 * hash) + VECTOR_FIELD_NUMBER;
        hash = (53 * hash) + getVectorList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.cardentify.data.CarListOuterClass.CarVector parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cardentify.data.CarListOuterClass.CarVector parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cardentify.data.CarListOuterClass.CarVector parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cardentify.data.CarListOuterClass.CarVector parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cardentify.data.CarListOuterClass.CarVector parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cardentify.data.CarListOuterClass.CarVector parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cardentify.data.CarListOuterClass.CarVector parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.cardentify.data.CarListOuterClass.CarVector parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.cardentify.data.CarListOuterClass.CarVector parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.cardentify.data.CarListOuterClass.CarVector parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.cardentify.data.CarListOuterClass.CarVector parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.cardentify.data.CarListOuterClass.CarVector parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.cardentify.data.CarListOuterClass.CarVector prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.cardentify.data.CarVector}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.cardentify.data.CarVector)
        net.cardentify.data.CarListOuterClass.CarVectorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.cardentify.data.CarListOuterClass.internal_static_net_cardentify_data_CarVector_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.cardentify.data.CarListOuterClass.internal_static_net_cardentify_data_CarVector_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.cardentify.data.CarListOuterClass.CarVector.class, net.cardentify.data.CarListOuterClass.CarVector.Builder.class);
      }

      // Construct using net.cardentify.data.CarListOuterClass.CarVector.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        vector_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.cardentify.data.CarListOuterClass.internal_static_net_cardentify_data_CarVector_descriptor;
      }

      public net.cardentify.data.CarListOuterClass.CarVector getDefaultInstanceForType() {
        return net.cardentify.data.CarListOuterClass.CarVector.getDefaultInstance();
      }

      public net.cardentify.data.CarListOuterClass.CarVector build() {
        net.cardentify.data.CarListOuterClass.CarVector result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.cardentify.data.CarListOuterClass.CarVector buildPartial() {
        net.cardentify.data.CarListOuterClass.CarVector result = new net.cardentify.data.CarListOuterClass.CarVector(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          vector_ = java.util.Collections.unmodifiableList(vector_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.vector_ = vector_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.cardentify.data.CarListOuterClass.CarVector) {
          return mergeFrom((net.cardentify.data.CarListOuterClass.CarVector)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.cardentify.data.CarListOuterClass.CarVector other) {
        if (other == net.cardentify.data.CarListOuterClass.CarVector.getDefaultInstance()) return this;
        if (!other.vector_.isEmpty()) {
          if (vector_.isEmpty()) {
            vector_ = other.vector_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVectorIsMutable();
            vector_.addAll(other.vector_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.cardentify.data.CarListOuterClass.CarVector parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.cardentify.data.CarListOuterClass.CarVector) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Float> vector_ = java.util.Collections.emptyList();
      private void ensureVectorIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          vector_ = new java.util.ArrayList<java.lang.Float>(vector_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated float vector = 1;</code>
       */
      public java.util.List<java.lang.Float>
          getVectorList() {
        return java.util.Collections.unmodifiableList(vector_);
      }
      /**
       * <code>repeated float vector = 1;</code>
       */
      public int getVectorCount() {
        return vector_.size();
      }
      /**
       * <code>repeated float vector = 1;</code>
       */
      public float getVector(int index) {
        return vector_.get(index);
      }
      /**
       * <code>repeated float vector = 1;</code>
       */
      public Builder setVector(
          int index, float value) {
        ensureVectorIsMutable();
        vector_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float vector = 1;</code>
       */
      public Builder addVector(float value) {
        ensureVectorIsMutable();
        vector_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float vector = 1;</code>
       */
      public Builder addAllVector(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureVectorIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vector_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float vector = 1;</code>
       */
      public Builder clearVector() {
        vector_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:net.cardentify.data.CarVector)
    }

    // @@protoc_insertion_point(class_scope:net.cardentify.data.CarVector)
    private static final net.cardentify.data.CarListOuterClass.CarVector DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.cardentify.data.CarListOuterClass.CarVector();
    }

    public static net.cardentify.data.CarListOuterClass.CarVector getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CarVector>
        PARSER = new com.google.protobuf.AbstractParser<CarVector>() {
      public CarVector parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CarVector(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CarVector> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CarVector> getParserForType() {
      return PARSER;
    }

    public net.cardentify.data.CarListOuterClass.CarVector getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CarInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.cardentify.data.CarInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
     */
    java.util.List<net.cardentify.data.CarListOuterClass.CarVector> 
        getVectorsList();
    /**
     * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
     */
    net.cardentify.data.CarListOuterClass.CarVector getVectors(int index);
    /**
     * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
     */
    int getVectorsCount();
    /**
     * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
     */
    java.util.List<? extends net.cardentify.data.CarListOuterClass.CarVectorOrBuilder> 
        getVectorsOrBuilderList();
    /**
     * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
     */
    net.cardentify.data.CarListOuterClass.CarVectorOrBuilder getVectorsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code net.cardentify.data.CarInfo}
   */
  public  static final class CarInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.cardentify.data.CarInfo)
      CarInfoOrBuilder {
    // Use CarInfo.newBuilder() to construct.
    private CarInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CarInfo() {
      name_ = "";
      vectors_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CarInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                vectors_ = new java.util.ArrayList<net.cardentify.data.CarListOuterClass.CarVector>();
                mutable_bitField0_ |= 0x00000002;
              }
              vectors_.add(
                  input.readMessage(net.cardentify.data.CarListOuterClass.CarVector.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          vectors_ = java.util.Collections.unmodifiableList(vectors_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.cardentify.data.CarListOuterClass.internal_static_net_cardentify_data_CarInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.cardentify.data.CarListOuterClass.internal_static_net_cardentify_data_CarInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.cardentify.data.CarListOuterClass.CarInfo.class, net.cardentify.data.CarListOuterClass.CarInfo.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VECTORS_FIELD_NUMBER = 2;
    private java.util.List<net.cardentify.data.CarListOuterClass.CarVector> vectors_;
    /**
     * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
     */
    public java.util.List<net.cardentify.data.CarListOuterClass.CarVector> getVectorsList() {
      return vectors_;
    }
    /**
     * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
     */
    public java.util.List<? extends net.cardentify.data.CarListOuterClass.CarVectorOrBuilder> 
        getVectorsOrBuilderList() {
      return vectors_;
    }
    /**
     * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
     */
    public int getVectorsCount() {
      return vectors_.size();
    }
    /**
     * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
     */
    public net.cardentify.data.CarListOuterClass.CarVector getVectors(int index) {
      return vectors_.get(index);
    }
    /**
     * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
     */
    public net.cardentify.data.CarListOuterClass.CarVectorOrBuilder getVectorsOrBuilder(
        int index) {
      return vectors_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      for (int i = 0; i < vectors_.size(); i++) {
        output.writeMessage(2, vectors_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      for (int i = 0; i < vectors_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, vectors_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.cardentify.data.CarListOuterClass.CarInfo)) {
        return super.equals(obj);
      }
      net.cardentify.data.CarListOuterClass.CarInfo other = (net.cardentify.data.CarListOuterClass.CarInfo) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getVectorsList()
          .equals(other.getVectorsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getVectorsCount() > 0) {
        hash = (37 * hash) + VECTORS_FIELD_NUMBER;
        hash = (53 * hash) + getVectorsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.cardentify.data.CarListOuterClass.CarInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cardentify.data.CarListOuterClass.CarInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cardentify.data.CarListOuterClass.CarInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cardentify.data.CarListOuterClass.CarInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cardentify.data.CarListOuterClass.CarInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cardentify.data.CarListOuterClass.CarInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cardentify.data.CarListOuterClass.CarInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.cardentify.data.CarListOuterClass.CarInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.cardentify.data.CarListOuterClass.CarInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.cardentify.data.CarListOuterClass.CarInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.cardentify.data.CarListOuterClass.CarInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.cardentify.data.CarListOuterClass.CarInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.cardentify.data.CarListOuterClass.CarInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.cardentify.data.CarInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.cardentify.data.CarInfo)
        net.cardentify.data.CarListOuterClass.CarInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.cardentify.data.CarListOuterClass.internal_static_net_cardentify_data_CarInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.cardentify.data.CarListOuterClass.internal_static_net_cardentify_data_CarInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.cardentify.data.CarListOuterClass.CarInfo.class, net.cardentify.data.CarListOuterClass.CarInfo.Builder.class);
      }

      // Construct using net.cardentify.data.CarListOuterClass.CarInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getVectorsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        if (vectorsBuilder_ == null) {
          vectors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          vectorsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.cardentify.data.CarListOuterClass.internal_static_net_cardentify_data_CarInfo_descriptor;
      }

      public net.cardentify.data.CarListOuterClass.CarInfo getDefaultInstanceForType() {
        return net.cardentify.data.CarListOuterClass.CarInfo.getDefaultInstance();
      }

      public net.cardentify.data.CarListOuterClass.CarInfo build() {
        net.cardentify.data.CarListOuterClass.CarInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.cardentify.data.CarListOuterClass.CarInfo buildPartial() {
        net.cardentify.data.CarListOuterClass.CarInfo result = new net.cardentify.data.CarListOuterClass.CarInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        if (vectorsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            vectors_ = java.util.Collections.unmodifiableList(vectors_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.vectors_ = vectors_;
        } else {
          result.vectors_ = vectorsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.cardentify.data.CarListOuterClass.CarInfo) {
          return mergeFrom((net.cardentify.data.CarListOuterClass.CarInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.cardentify.data.CarListOuterClass.CarInfo other) {
        if (other == net.cardentify.data.CarListOuterClass.CarInfo.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (vectorsBuilder_ == null) {
          if (!other.vectors_.isEmpty()) {
            if (vectors_.isEmpty()) {
              vectors_ = other.vectors_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureVectorsIsMutable();
              vectors_.addAll(other.vectors_);
            }
            onChanged();
          }
        } else {
          if (!other.vectors_.isEmpty()) {
            if (vectorsBuilder_.isEmpty()) {
              vectorsBuilder_.dispose();
              vectorsBuilder_ = null;
              vectors_ = other.vectors_;
              bitField0_ = (bitField0_ & ~0x00000002);
              vectorsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getVectorsFieldBuilder() : null;
            } else {
              vectorsBuilder_.addAllMessages(other.vectors_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.cardentify.data.CarListOuterClass.CarInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.cardentify.data.CarListOuterClass.CarInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<net.cardentify.data.CarListOuterClass.CarVector> vectors_ =
        java.util.Collections.emptyList();
      private void ensureVectorsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          vectors_ = new java.util.ArrayList<net.cardentify.data.CarListOuterClass.CarVector>(vectors_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.cardentify.data.CarListOuterClass.CarVector, net.cardentify.data.CarListOuterClass.CarVector.Builder, net.cardentify.data.CarListOuterClass.CarVectorOrBuilder> vectorsBuilder_;

      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public java.util.List<net.cardentify.data.CarListOuterClass.CarVector> getVectorsList() {
        if (vectorsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(vectors_);
        } else {
          return vectorsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public int getVectorsCount() {
        if (vectorsBuilder_ == null) {
          return vectors_.size();
        } else {
          return vectorsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public net.cardentify.data.CarListOuterClass.CarVector getVectors(int index) {
        if (vectorsBuilder_ == null) {
          return vectors_.get(index);
        } else {
          return vectorsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public Builder setVectors(
          int index, net.cardentify.data.CarListOuterClass.CarVector value) {
        if (vectorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVectorsIsMutable();
          vectors_.set(index, value);
          onChanged();
        } else {
          vectorsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public Builder setVectors(
          int index, net.cardentify.data.CarListOuterClass.CarVector.Builder builderForValue) {
        if (vectorsBuilder_ == null) {
          ensureVectorsIsMutable();
          vectors_.set(index, builderForValue.build());
          onChanged();
        } else {
          vectorsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public Builder addVectors(net.cardentify.data.CarListOuterClass.CarVector value) {
        if (vectorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVectorsIsMutable();
          vectors_.add(value);
          onChanged();
        } else {
          vectorsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public Builder addVectors(
          int index, net.cardentify.data.CarListOuterClass.CarVector value) {
        if (vectorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVectorsIsMutable();
          vectors_.add(index, value);
          onChanged();
        } else {
          vectorsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public Builder addVectors(
          net.cardentify.data.CarListOuterClass.CarVector.Builder builderForValue) {
        if (vectorsBuilder_ == null) {
          ensureVectorsIsMutable();
          vectors_.add(builderForValue.build());
          onChanged();
        } else {
          vectorsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public Builder addVectors(
          int index, net.cardentify.data.CarListOuterClass.CarVector.Builder builderForValue) {
        if (vectorsBuilder_ == null) {
          ensureVectorsIsMutable();
          vectors_.add(index, builderForValue.build());
          onChanged();
        } else {
          vectorsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public Builder addAllVectors(
          java.lang.Iterable<? extends net.cardentify.data.CarListOuterClass.CarVector> values) {
        if (vectorsBuilder_ == null) {
          ensureVectorsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, vectors_);
          onChanged();
        } else {
          vectorsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public Builder clearVectors() {
        if (vectorsBuilder_ == null) {
          vectors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          vectorsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public Builder removeVectors(int index) {
        if (vectorsBuilder_ == null) {
          ensureVectorsIsMutable();
          vectors_.remove(index);
          onChanged();
        } else {
          vectorsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public net.cardentify.data.CarListOuterClass.CarVector.Builder getVectorsBuilder(
          int index) {
        return getVectorsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public net.cardentify.data.CarListOuterClass.CarVectorOrBuilder getVectorsOrBuilder(
          int index) {
        if (vectorsBuilder_ == null) {
          return vectors_.get(index);  } else {
          return vectorsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public java.util.List<? extends net.cardentify.data.CarListOuterClass.CarVectorOrBuilder> 
           getVectorsOrBuilderList() {
        if (vectorsBuilder_ != null) {
          return vectorsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(vectors_);
        }
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public net.cardentify.data.CarListOuterClass.CarVector.Builder addVectorsBuilder() {
        return getVectorsFieldBuilder().addBuilder(
            net.cardentify.data.CarListOuterClass.CarVector.getDefaultInstance());
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public net.cardentify.data.CarListOuterClass.CarVector.Builder addVectorsBuilder(
          int index) {
        return getVectorsFieldBuilder().addBuilder(
            index, net.cardentify.data.CarListOuterClass.CarVector.getDefaultInstance());
      }
      /**
       * <code>repeated .net.cardentify.data.CarVector vectors = 2;</code>
       */
      public java.util.List<net.cardentify.data.CarListOuterClass.CarVector.Builder> 
           getVectorsBuilderList() {
        return getVectorsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.cardentify.data.CarListOuterClass.CarVector, net.cardentify.data.CarListOuterClass.CarVector.Builder, net.cardentify.data.CarListOuterClass.CarVectorOrBuilder> 
          getVectorsFieldBuilder() {
        if (vectorsBuilder_ == null) {
          vectorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              net.cardentify.data.CarListOuterClass.CarVector, net.cardentify.data.CarListOuterClass.CarVector.Builder, net.cardentify.data.CarListOuterClass.CarVectorOrBuilder>(
                  vectors_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          vectors_ = null;
        }
        return vectorsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:net.cardentify.data.CarInfo)
    }

    // @@protoc_insertion_point(class_scope:net.cardentify.data.CarInfo)
    private static final net.cardentify.data.CarListOuterClass.CarInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.cardentify.data.CarListOuterClass.CarInfo();
    }

    public static net.cardentify.data.CarListOuterClass.CarInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CarInfo>
        PARSER = new com.google.protobuf.AbstractParser<CarInfo>() {
      public CarInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CarInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CarInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CarInfo> getParserForType() {
      return PARSER;
    }

    public net.cardentify.data.CarListOuterClass.CarInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CarListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.cardentify.data.CarList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
     */
    java.util.List<net.cardentify.data.CarListOuterClass.CarInfo> 
        getCarsList();
    /**
     * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
     */
    net.cardentify.data.CarListOuterClass.CarInfo getCars(int index);
    /**
     * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
     */
    int getCarsCount();
    /**
     * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
     */
    java.util.List<? extends net.cardentify.data.CarListOuterClass.CarInfoOrBuilder> 
        getCarsOrBuilderList();
    /**
     * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
     */
    net.cardentify.data.CarListOuterClass.CarInfoOrBuilder getCarsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code net.cardentify.data.CarList}
   */
  public  static final class CarList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.cardentify.data.CarList)
      CarListOrBuilder {
    // Use CarList.newBuilder() to construct.
    private CarList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CarList() {
      cars_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CarList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                cars_ = new java.util.ArrayList<net.cardentify.data.CarListOuterClass.CarInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              cars_.add(
                  input.readMessage(net.cardentify.data.CarListOuterClass.CarInfo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          cars_ = java.util.Collections.unmodifiableList(cars_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.cardentify.data.CarListOuterClass.internal_static_net_cardentify_data_CarList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.cardentify.data.CarListOuterClass.internal_static_net_cardentify_data_CarList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.cardentify.data.CarListOuterClass.CarList.class, net.cardentify.data.CarListOuterClass.CarList.Builder.class);
    }

    public static final int CARS_FIELD_NUMBER = 1;
    private java.util.List<net.cardentify.data.CarListOuterClass.CarInfo> cars_;
    /**
     * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
     */
    public java.util.List<net.cardentify.data.CarListOuterClass.CarInfo> getCarsList() {
      return cars_;
    }
    /**
     * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
     */
    public java.util.List<? extends net.cardentify.data.CarListOuterClass.CarInfoOrBuilder> 
        getCarsOrBuilderList() {
      return cars_;
    }
    /**
     * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
     */
    public int getCarsCount() {
      return cars_.size();
    }
    /**
     * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
     */
    public net.cardentify.data.CarListOuterClass.CarInfo getCars(int index) {
      return cars_.get(index);
    }
    /**
     * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
     */
    public net.cardentify.data.CarListOuterClass.CarInfoOrBuilder getCarsOrBuilder(
        int index) {
      return cars_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < cars_.size(); i++) {
        output.writeMessage(1, cars_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < cars_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, cars_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.cardentify.data.CarListOuterClass.CarList)) {
        return super.equals(obj);
      }
      net.cardentify.data.CarListOuterClass.CarList other = (net.cardentify.data.CarListOuterClass.CarList) obj;

      boolean result = true;
      result = result && getCarsList()
          .equals(other.getCarsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCarsCount() > 0) {
        hash = (37 * hash) + CARS_FIELD_NUMBER;
        hash = (53 * hash) + getCarsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.cardentify.data.CarListOuterClass.CarList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cardentify.data.CarListOuterClass.CarList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cardentify.data.CarListOuterClass.CarList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cardentify.data.CarListOuterClass.CarList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cardentify.data.CarListOuterClass.CarList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.cardentify.data.CarListOuterClass.CarList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.cardentify.data.CarListOuterClass.CarList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.cardentify.data.CarListOuterClass.CarList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.cardentify.data.CarListOuterClass.CarList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.cardentify.data.CarListOuterClass.CarList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.cardentify.data.CarListOuterClass.CarList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.cardentify.data.CarListOuterClass.CarList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.cardentify.data.CarListOuterClass.CarList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.cardentify.data.CarList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.cardentify.data.CarList)
        net.cardentify.data.CarListOuterClass.CarListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.cardentify.data.CarListOuterClass.internal_static_net_cardentify_data_CarList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.cardentify.data.CarListOuterClass.internal_static_net_cardentify_data_CarList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.cardentify.data.CarListOuterClass.CarList.class, net.cardentify.data.CarListOuterClass.CarList.Builder.class);
      }

      // Construct using net.cardentify.data.CarListOuterClass.CarList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCarsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (carsBuilder_ == null) {
          cars_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          carsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.cardentify.data.CarListOuterClass.internal_static_net_cardentify_data_CarList_descriptor;
      }

      public net.cardentify.data.CarListOuterClass.CarList getDefaultInstanceForType() {
        return net.cardentify.data.CarListOuterClass.CarList.getDefaultInstance();
      }

      public net.cardentify.data.CarListOuterClass.CarList build() {
        net.cardentify.data.CarListOuterClass.CarList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.cardentify.data.CarListOuterClass.CarList buildPartial() {
        net.cardentify.data.CarListOuterClass.CarList result = new net.cardentify.data.CarListOuterClass.CarList(this);
        int from_bitField0_ = bitField0_;
        if (carsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            cars_ = java.util.Collections.unmodifiableList(cars_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.cars_ = cars_;
        } else {
          result.cars_ = carsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.cardentify.data.CarListOuterClass.CarList) {
          return mergeFrom((net.cardentify.data.CarListOuterClass.CarList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.cardentify.data.CarListOuterClass.CarList other) {
        if (other == net.cardentify.data.CarListOuterClass.CarList.getDefaultInstance()) return this;
        if (carsBuilder_ == null) {
          if (!other.cars_.isEmpty()) {
            if (cars_.isEmpty()) {
              cars_ = other.cars_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCarsIsMutable();
              cars_.addAll(other.cars_);
            }
            onChanged();
          }
        } else {
          if (!other.cars_.isEmpty()) {
            if (carsBuilder_.isEmpty()) {
              carsBuilder_.dispose();
              carsBuilder_ = null;
              cars_ = other.cars_;
              bitField0_ = (bitField0_ & ~0x00000001);
              carsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCarsFieldBuilder() : null;
            } else {
              carsBuilder_.addAllMessages(other.cars_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.cardentify.data.CarListOuterClass.CarList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.cardentify.data.CarListOuterClass.CarList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<net.cardentify.data.CarListOuterClass.CarInfo> cars_ =
        java.util.Collections.emptyList();
      private void ensureCarsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          cars_ = new java.util.ArrayList<net.cardentify.data.CarListOuterClass.CarInfo>(cars_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.cardentify.data.CarListOuterClass.CarInfo, net.cardentify.data.CarListOuterClass.CarInfo.Builder, net.cardentify.data.CarListOuterClass.CarInfoOrBuilder> carsBuilder_;

      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public java.util.List<net.cardentify.data.CarListOuterClass.CarInfo> getCarsList() {
        if (carsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cars_);
        } else {
          return carsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public int getCarsCount() {
        if (carsBuilder_ == null) {
          return cars_.size();
        } else {
          return carsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public net.cardentify.data.CarListOuterClass.CarInfo getCars(int index) {
        if (carsBuilder_ == null) {
          return cars_.get(index);
        } else {
          return carsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public Builder setCars(
          int index, net.cardentify.data.CarListOuterClass.CarInfo value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.set(index, value);
          onChanged();
        } else {
          carsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public Builder setCars(
          int index, net.cardentify.data.CarListOuterClass.CarInfo.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.set(index, builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public Builder addCars(net.cardentify.data.CarListOuterClass.CarInfo value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.add(value);
          onChanged();
        } else {
          carsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public Builder addCars(
          int index, net.cardentify.data.CarListOuterClass.CarInfo value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.add(index, value);
          onChanged();
        } else {
          carsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public Builder addCars(
          net.cardentify.data.CarListOuterClass.CarInfo.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.add(builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public Builder addCars(
          int index, net.cardentify.data.CarListOuterClass.CarInfo.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.add(index, builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public Builder addAllCars(
          java.lang.Iterable<? extends net.cardentify.data.CarListOuterClass.CarInfo> values) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cars_);
          onChanged();
        } else {
          carsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public Builder clearCars() {
        if (carsBuilder_ == null) {
          cars_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          carsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public Builder removeCars(int index) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.remove(index);
          onChanged();
        } else {
          carsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public net.cardentify.data.CarListOuterClass.CarInfo.Builder getCarsBuilder(
          int index) {
        return getCarsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public net.cardentify.data.CarListOuterClass.CarInfoOrBuilder getCarsOrBuilder(
          int index) {
        if (carsBuilder_ == null) {
          return cars_.get(index);  } else {
          return carsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public java.util.List<? extends net.cardentify.data.CarListOuterClass.CarInfoOrBuilder> 
           getCarsOrBuilderList() {
        if (carsBuilder_ != null) {
          return carsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cars_);
        }
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public net.cardentify.data.CarListOuterClass.CarInfo.Builder addCarsBuilder() {
        return getCarsFieldBuilder().addBuilder(
            net.cardentify.data.CarListOuterClass.CarInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public net.cardentify.data.CarListOuterClass.CarInfo.Builder addCarsBuilder(
          int index) {
        return getCarsFieldBuilder().addBuilder(
            index, net.cardentify.data.CarListOuterClass.CarInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .net.cardentify.data.CarInfo cars = 1;</code>
       */
      public java.util.List<net.cardentify.data.CarListOuterClass.CarInfo.Builder> 
           getCarsBuilderList() {
        return getCarsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.cardentify.data.CarListOuterClass.CarInfo, net.cardentify.data.CarListOuterClass.CarInfo.Builder, net.cardentify.data.CarListOuterClass.CarInfoOrBuilder> 
          getCarsFieldBuilder() {
        if (carsBuilder_ == null) {
          carsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              net.cardentify.data.CarListOuterClass.CarInfo, net.cardentify.data.CarListOuterClass.CarInfo.Builder, net.cardentify.data.CarListOuterClass.CarInfoOrBuilder>(
                  cars_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          cars_ = null;
        }
        return carsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:net.cardentify.data.CarList)
    }

    // @@protoc_insertion_point(class_scope:net.cardentify.data.CarList)
    private static final net.cardentify.data.CarListOuterClass.CarList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.cardentify.data.CarListOuterClass.CarList();
    }

    public static net.cardentify.data.CarListOuterClass.CarList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CarList>
        PARSER = new com.google.protobuf.AbstractParser<CarList>() {
      public CarList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CarList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CarList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CarList> getParserForType() {
      return PARSER;
    }

    public net.cardentify.data.CarListOuterClass.CarList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_cardentify_data_CarVector_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_cardentify_data_CarVector_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_cardentify_data_CarInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_cardentify_data_CarInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_cardentify_data_CarList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_cardentify_data_CarList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCarList.proto\022\023net.cardentify.data\"\033\n\t" +
      "CarVector\022\016\n\006vector\030\001 \003(\002\"H\n\007CarInfo\022\014\n\004" +
      "name\030\001 \001(\t\022/\n\007vectors\030\002 \003(\0132\036.net.carden" +
      "tify.data.CarVector\"5\n\007CarList\022*\n\004cars\030\001" +
      " \003(\0132\034.net.cardentify.data.CarInfob\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_net_cardentify_data_CarVector_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_cardentify_data_CarVector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_cardentify_data_CarVector_descriptor,
        new java.lang.String[] { "Vector", });
    internal_static_net_cardentify_data_CarInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_cardentify_data_CarInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_cardentify_data_CarInfo_descriptor,
        new java.lang.String[] { "Name", "Vectors", });
    internal_static_net_cardentify_data_CarList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_net_cardentify_data_CarList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_cardentify_data_CarList_descriptor,
        new java.lang.String[] { "Cars", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
